/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/Map/map.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Map(props) {
	const { nodes, materials } = useGLTF("/models/Map/map.gltf");
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Object_10.geometry} material={materials.material_17} />
			<mesh geometry={nodes.Object_11.geometry} material={materials.material_18} />
			<mesh geometry={nodes.Object_12.geometry} material={materials.material_19} />
			<mesh geometry={nodes.Object_13.geometry} material={materials.material_20} />
			<mesh geometry={nodes.Object_14.geometry} material={materials.material_22} />
			<mesh geometry={nodes.Object_15.geometry} material={materials.material_23} />
			<mesh geometry={nodes.Object_17.geometry} material={materials.material_25} />
			<mesh geometry={nodes.Object_18.geometry} material={materials.material_26} />
			<mesh geometry={nodes.Object_19.geometry} material={materials.material_27} />
			<mesh geometry={nodes.Object_2.geometry} material={materials.material_0} />
			<mesh geometry={nodes.Object_20.geometry} material={materials.material_28} />
			<mesh geometry={nodes.Object_21.geometry} material={materials.material_29} />
			<mesh geometry={nodes.Object_23.geometry} material={materials.material_30} />
			<mesh geometry={nodes.Object_24.geometry} material={materials.material_4} />
			<mesh geometry={nodes.Object_25.geometry} material={materials.material_5} />
			<mesh geometry={nodes.Object_26.geometry} material={materials.material_6} />
			<mesh geometry={nodes.Object_27.geometry} material={materials.material_7} />
			<mesh geometry={nodes.Object_28.geometry} material={materials.material_8} />
			<mesh geometry={nodes.Object_29.geometry} material={materials.material_1} />
			<mesh geometry={nodes.Object_3.geometry} material={materials.material_10} />
			<mesh geometry={nodes.Object_30.geometry} material={materials.material_2} />
			<mesh geometry={nodes.Object_31.geometry} material={materials.material_21} />
			<mesh geometry={nodes.Object_32.geometry} material={materials.material_31} />
			<mesh geometry={nodes.Object_33.geometry} material={materials.material_32} />
			<mesh geometry={nodes.Object_34.geometry} material={materials.material_33} />
			<mesh geometry={nodes.Object_35.geometry} material={materials.material_9} />
			<mesh geometry={nodes.Object_4.geometry} material={materials.material_11} />
			<mesh geometry={nodes.Object_5.geometry} material={materials.material_12} />
			<mesh geometry={nodes.Object_6.geometry} material={materials.material_13} />
			<mesh geometry={nodes.Object_7.geometry} material={materials.material_14} />
			<mesh geometry={nodes.Object_8.geometry} material={materials.material_15} />
			<mesh geometry={nodes.Object_9.geometry} material={materials.material_16} />
		</group>
	);
}

useGLTF.preload("/models/Map/map.gltf");
