/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/Map/map.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Map(props) {
	const { scene, nodes, materials } = useGLTF("/models/Map/map.gltf");
	scene.traverse((obj) => {
		console.log(obj);
		if (obj.type === "Mesh") {
			obj.castShadow = true;
			obj.receiveShadow = true;
			obj.frustumCulled = true;
		}
	});

	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes["air-conditioning001_air-conditioning_0"].geometry}
				material={materials["air-conditioning"]}
			/>
			<mesh geometry={nodes.Armchair_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair001_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair002_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair003_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair004_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair005_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair006_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair007_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair008_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair009_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair010_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair011_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair012_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair013_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair014_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.Armchair015_Armchair_0.geometry} material={materials.Armchair} />
			<mesh geometry={nodes.AsphaltDamaged_AsphaltDamaged_0.geometry} material={materials.AsphaltDamaged} />
			<mesh geometry={nodes.AsphaltDamaged_sidewalk_01_0.geometry} material={materials.sidewalk_01} />
			<mesh geometry={nodes.Background_Background_0.geometry} material={materials.Background} />
			<mesh geometry={nodes.basket002_Shelf_FR_0.geometry} material={materials.Shelf_FR} />
			<mesh geometry={nodes.basket003_Shelf_FR_0.geometry} material={materials.Shelf_FR} />
			<mesh geometry={nodes.basket004_Shelf_FR_0.geometry} material={materials.Shelf_FR} />
			<mesh geometry={nodes.basket005_Shelf_FR_0.geometry} material={materials.Shelf_FR} />
			<mesh geometry={nodes.Building_Building_0.geometry} material={materials.Building} />
			<mesh geometry={nodes.Building_Roof_tiles_0.geometry} material={materials.Roof_tiles} />
			<mesh geometry={nodes.Building_Wall_0.geometry} material={materials.Wall} />
			<mesh geometry={nodes.Building001_Building_0.geometry} material={materials.Building} />
			<mesh geometry={nodes.Building001_Roof_tiles_0.geometry} material={materials.Roof_tiles} />
			<mesh geometry={nodes.Building001_Wall_0.geometry} material={materials.Wall} />
			<mesh geometry={nodes.Building002_Building_0.geometry} material={materials.Building} />
			<mesh geometry={nodes.Building002_Roof_tiles_0.geometry} material={materials.Roof_tiles} />
			<mesh geometry={nodes.Building002_Wall_0.geometry} material={materials.Wall} />
			<mesh geometry={nodes.Building003_Building_0.geometry} material={materials.Building} />
			<mesh geometry={nodes.Building003_Roof_tiles_0.geometry} material={materials.Roof_tiles} />
			<mesh geometry={nodes.Building003_Wall_0.geometry} material={materials.Wall} />
			<mesh geometry={nodes.Building_01_Building_01_0.geometry} material={materials.Building_01} />
			<mesh geometry={nodes.Building_01001_Building_01_0.geometry} material={materials.Building_01} />
			<mesh geometry={nodes.Building_02_Building_02_0.geometry} material={materials.Building_02} />
			<mesh geometry={nodes.Building_02001_Building_02_0.geometry} material={materials.Building_02} />
			<mesh geometry={nodes.Building_02002_Building_02_0.geometry} material={materials.Building_02} />
			<mesh geometry={nodes.Building_02003_Building_02_0.geometry} material={materials.Building_02} />
			<mesh geometry={nodes.Building_02004_Building_02_0.geometry} material={materials.Building_02} />
			<mesh geometry={nodes.Building_02005_Building_02_0.geometry} material={materials.Building_02} />
			<mesh geometry={nodes.BurgerPiz_Blu_0.geometry} material={materials.material} />
			<mesh geometry={nodes.BurgerPiz_BrickPainted_0.geometry} material={materials.BrickPainted} />
			<mesh geometry={nodes.BurgerPiz_Metal_0.geometry} material={materials.Metal} />
			<mesh geometry={nodes.BurgerPiz_Plaster_0.geometry} material={materials.Plaster} />
			<mesh geometry={nodes.BurgerPiz_Plaster_01_0.geometry} material={materials.Plaster_01} />
			<mesh geometry={nodes.BurgerPiz_Plaster_02_0.geometry} material={materials.Plaster_02} />
			<mesh geometry={nodes.BurgerPiz_Roof_tiles_0.geometry} material={materials.Roof_tiles} />
			<mesh geometry={nodes.BurgerPiz_L_Emissor_0.geometry} material={materials.Emissor} />
			<mesh geometry={nodes.BurgerPiz_L001_Orange_0.geometry} material={materials.Orange} />
			<mesh geometry={nodes.cardboard_boxes001_cardboard_boxes_0.geometry} material={materials.cardboard_boxes} />
			<mesh geometry={nodes.cardboard_boxes002_cardboard_boxes_0.geometry} material={materials.cardboard_boxes} />
			<mesh geometry={nodes.cardboard_boxes003_cardboard_boxes_0.geometry} material={materials.cardboard_boxes} />
			<mesh geometry={nodes.cardboard_boxes004_cardboard_boxes_0.geometry} material={materials.cardboard_boxes} />
			<mesh geometry={nodes.cardboard_boxes005_cardboard_boxes_0.geometry} material={materials.cardboard_boxes} />
			<mesh geometry={nodes.cardboard_boxes006_cardboard_boxes_0.geometry} material={materials.cardboard_boxes} />
			<mesh geometry={nodes.cardboard_boxes007_cardboard_boxes_0.geometry} material={materials.cardboard_boxes} />
			<mesh
				geometry={nodes.cardboard_boxes_01001_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_01002_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_01003_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_01004_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_01005_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_01006_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_02001_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_02002_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_02003_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_02004_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_02005_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_02006_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_02007_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_02008_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_03001_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_03002_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_03003_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_03004_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_03005_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_03006_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh
				geometry={nodes.cardboard_boxes_03007_cardboard_boxes_0.geometry}
				material={materials.cardboard_boxes}
			/>
			<mesh geometry={nodes.Cash_register_Cash_register_0.geometry} material={materials.Cash_register} />
			<mesh geometry={nodes.Cash_register_Terminal_0.geometry} material={materials.Terminal} />
			<mesh geometry={nodes.Cash_register_01_Cash_register_0.geometry} material={materials.Cash_register} />
			<mesh geometry={nodes.Cash_register_01_Terminal_0.geometry} material={materials.Terminal} />
			<mesh geometry={nodes.Cash_register_02_Cash_register_0.geometry} material={materials.Cash_register} />
			<mesh geometry={nodes.Cash_register_02_Terminal_0.geometry} material={materials.Terminal} />
			<mesh geometry={nodes.Ceiling_Office_Ceiling_0.geometry} material={materials.Office_Ceiling} />
			<mesh geometry={nodes.Ceiling_A_Plaster_01_0.geometry} material={materials.Plaster_01} />
			<mesh geometry={nodes.Chair_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair001_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair002_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair003_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair004_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair005_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair006_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair007_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair008_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair009_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair010_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair011_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair012_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair013_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair014_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair015_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair016_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair017_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair018_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair019_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair020_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair021_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair022_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.Chair023_Chair_0.geometry} material={materials.Chair} />
			<mesh geometry={nodes.counter_ColorWhite_0.geometry} material={materials.ColorWhite} />
			<mesh geometry={nodes.counter_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.counter_01_ColorWhite_0.geometry} material={materials.ColorWhite} />
			<mesh geometry={nodes.counter_01_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.counter_02_ColorWhite_0.geometry} material={materials.ColorWhite} />
			<mesh geometry={nodes.counter_02_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.Door_Door_02_0.geometry} material={materials.Door_02} />
			<mesh geometry={nodes.Door_01_Door_02_0.geometry} material={materials.Door_02} />
			<mesh geometry={nodes.Door_C_Door_0.geometry} material={materials.Door} />
			<mesh geometry={nodes.Door_C_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Door_F_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Door_F_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Door_F_Orange_0.geometry} material={materials.Orange} />
			<mesh geometry={nodes.Door_F001_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Door_F001_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Door_F001_Orange_0.geometry} material={materials.Orange} />
			<mesh geometry={nodes.Door_Fr_Door_03_0.geometry} material={materials.Door_03} />
			<mesh geometry={nodes.Door_Fr_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Door_W_Door_01_0.geometry} material={materials.Door_01} />
			<mesh geometry={nodes.Door_W_Sign_0.geometry} material={materials.Sign} />
			<mesh geometry={nodes.Door_W_01_Door_01_0.geometry} material={materials.Door_01} />
			<mesh geometry={nodes.Door_W_01_Sign_0.geometry} material={materials.Sign} />
			<mesh geometry={nodes.Floor_Metal_0.geometry} material={materials.Metal} />
			<mesh geometry={nodes.Floor_Metal_01_0.geometry} material={materials.Metal_01} />
			<mesh geometry={nodes.Floor_Tiles_0.geometry} material={materials.Tiles} />
			<mesh geometry={nodes.Floor_TilesPlain_0.geometry} material={materials.TilesPlain} />
			<mesh geometry={nodes.Floor_WoodFloor_0.geometry} material={materials.WoodFloor} />
			<mesh geometry={nodes.garden_Grass_0.geometry} material={materials.Grass} />
			<mesh geometry={nodes.garden_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.Grass_Grass_0.geometry} material={materials.Grass} />
			<mesh geometry={nodes.Grill001_Grill_0.geometry} material={materials.Grill} />
			<mesh geometry={nodes.Grill002_Grill_0.geometry} material={materials.Grill} />
			<mesh geometry={nodes.Grill003_Grill_0.geometry} material={materials.Grill} />
			<mesh geometry={nodes.kitchen_hood_Material_0.geometry} material={materials["Material.001"]} />
			<mesh geometry={nodes.kitchen_hood_Metal_0.geometry} material={materials.Metal} />
			<mesh geometry={nodes.kitchen_hood001_Material_0.geometry} material={materials["Material.001"]} />
			<mesh geometry={nodes.kitchen_hood001_Metal_0.geometry} material={materials.Metal} />
			<mesh geometry={nodes.L_Orange_0.geometry} material={materials.Orange} />
			<mesh geometry={nodes.Lamppost_001_Lamppost_0.geometry} material={materials.Lamppost} />
			<mesh geometry={nodes.Lamppost_001001_Lamppost_0.geometry} material={materials.Lamppost} />
			<mesh geometry={nodes.Lamppost_001002_Lamppost_0.geometry} material={materials.Lamppost} />
			<mesh geometry={nodes.Lamppost_001003_Lamppost_0.geometry} material={materials.Lamppost} />
			<mesh geometry={nodes.Lamppost_001004_Lamppost_0.geometry} material={materials.Lamppost} />
			<mesh geometry={nodes.Lamppost_001005_Lamppost_0.geometry} material={materials.Lamppost} />
			<mesh geometry={nodes.Lamppost_001006_Lamppost_0.geometry} material={materials.Lamppost} />
			<mesh geometry={nodes.Lamppost_001007_Lamppost_0.geometry} material={materials.Lamppost} />
			<mesh geometry={nodes.Lamppost_001008_Lamppost_0.geometry} material={materials.Lamppost} />
			<mesh geometry={nodes.Lamppost_001009_Lamppost_0.geometry} material={materials.Lamppost} />
			<mesh geometry={nodes.Lamppost_001010_Lamppost_0.geometry} material={materials.Lamppost} />
			<mesh geometry={nodes.Lamppost_001011_Lamppost_0.geometry} material={materials.Lamppost} />
			<mesh geometry={nodes.Light_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light001_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light002_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light003_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light004_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light005_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light006_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light007_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light008_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light009_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light010_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light011_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light012_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light013_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light014_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light015_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light016_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light017_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light018_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light019_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light020_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light021_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light022_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light023_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light024_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light025_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light026_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light027_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light028_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light029_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light030_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light031_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light032_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light033_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light034_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light035_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Light036_Light_0.geometry} material={materials.Light} />
			<mesh geometry={nodes.Lines_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines001_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines002_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines003_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines004_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines005_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines006_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines007_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines008_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines009_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines010_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines011_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines012_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines013_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines014_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines015_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines016_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines017_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines018_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines019_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines020_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines021_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines022_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines023_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines024_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines025_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines026_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines027_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Lines028_Lines_0.geometry} material={materials.Lines} />
			<mesh geometry={nodes.Menu_menu_burger_0.geometry} material={materials.menu_burger} />
			<mesh geometry={nodes.Menu_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Menu001_menu_burger_0.geometry} material={materials.menu_burger} />
			<mesh geometry={nodes.Menu001_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.Menu002_menu_burger_0.geometry} material={materials.menu_burger} />
			<mesh geometry={nodes.Menu002_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.Mirror_Mirror_0.geometry} material={materials.Mirror} />
			<mesh geometry={nodes.Mirror001_Mirror_0.geometry} material={materials.Mirror} />
			<mesh geometry={nodes.Mirror002_Mirror_0.geometry} material={materials.Mirror} />
			<mesh geometry={nodes.Paper_dispenser001_Paper_dispenser_0.geometry} material={materials.Paper_dispenser} />
			<mesh geometry={nodes.Paper_dispenser002_Paper_dispenser_0.geometry} material={materials.Paper_dispenser} />
			<mesh geometry={nodes.Paper_dispenser003_Paper_dispenser_0.geometry} material={materials.Paper_dispenser} />
			<mesh geometry={nodes.Paper_dispenser004_Paper_dispenser_0.geometry} material={materials.Paper_dispenser} />
			<mesh geometry={nodes.Paper_dispenser005_Paper_dispenser_0.geometry} material={materials.Paper_dispenser} />
			<mesh geometry={nodes.Paper_dispenser006_Paper_dispenser_0.geometry} material={materials.Paper_dispenser} />
			<mesh geometry={nodes.Paper_dispenser007_Paper_dispenser_0.geometry} material={materials.Paper_dispenser} />
			<mesh geometry={nodes.Paper_dispenser008_Paper_dispenser_0.geometry} material={materials.Paper_dispenser} />
			<mesh geometry={nodes.Paper_dispenser009_Paper_dispenser_0.geometry} material={materials.Paper_dispenser} />
			<mesh geometry={nodes.Plant_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plant001_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plant002_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants001_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants002_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants003_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants004_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants005_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants006_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants007_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants008_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants009_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants010_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants011_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants012_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants013_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants014_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants015_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants016_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants017_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants018_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants019_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants020_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants021_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants022_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants023_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants024_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants025_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants026_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants027_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants028_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants029_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants030_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants031_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants032_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants033_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants034_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants035_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants036_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants037_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants038_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants039_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants040_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants041_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants042_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants043_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants044_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants045_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants046_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants047_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants048_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants049_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants050_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants051_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants052_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants053_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants054_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants055_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants056_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants057_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants058_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants059_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants060_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants061_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.Plants062_Plants_0.geometry} material={materials.Plants} />
			<mesh geometry={nodes.plants_flowers_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers001_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers002_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers003_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers004_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers005_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers006_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers007_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers008_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers009_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers010_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers011_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers012_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers013_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers014_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers015_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers016_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers017_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers018_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers019_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers020_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers021_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers022_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers023_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers024_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers025_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.plants_flowers026_plants_flowers_0.geometry} material={materials.plants_flowers} />
			<mesh geometry={nodes.Refrijerator_M001_Refrijerator_M_0.geometry} material={materials.Refrijerator_M} />
			<mesh geometry={nodes.Refrijerator_M_D001_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Refrijerator_M_D001_Refrijerator_M_0.geometry} material={materials.Refrijerator_M} />
			<mesh geometry={nodes.Resources001_Resources_0.geometry} material={materials.Resources} />
			<mesh geometry={nodes.Resources002_Resources_0.geometry} material={materials.Resources} />
			<mesh geometry={nodes.Resources003_Resources_0.geometry} material={materials.Resources} />
			<mesh geometry={nodes.Resources004_Resources_0.geometry} material={materials.Resources} />
			<mesh geometry={nodes.Resources005_Resources_0.geometry} material={materials.Resources} />
			<mesh geometry={nodes.Resources006_Resources_0.geometry} material={materials.Resources} />
			<mesh geometry={nodes.Resources007_Shelf_fd_0.geometry} material={materials.Shelf_fd} />
			<mesh geometry={nodes.Resources008_Shelf_fd_0.geometry} material={materials.Shelf_fd} />
			<mesh geometry={nodes.Resources009_Shelf_fd_0.geometry} material={materials.Shelf_fd} />
			<mesh geometry={nodes.Resources010_Shelf_fd_0.geometry} material={materials.Shelf_fd} />
			<mesh geometry={nodes.Resources011_Shelf_fd_0.geometry} material={materials.Shelf_fd} />
			<mesh geometry={nodes.Resources012_Shelf_fd_0.geometry} material={materials.Shelf_fd} />
			<mesh geometry={nodes.Resources013_Shelf_fd_0.geometry} material={materials.Shelf_fd} />
			<mesh geometry={nodes.Resources014_Resources_0.geometry} material={materials.Resources} />
			<mesh geometry={nodes.RooftilesMetal_BrickPainted_0.geometry} material={materials.BrickPainted} />
			<mesh geometry={nodes.RooftilesMetal_RooftilesMetal_0.geometry} material={materials.RooftilesMetal} />
			<mesh geometry={nodes.RooftilesMetal_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.Shelf_B001_Shelf_B_0.geometry} material={materials.Shelf_B} />
			<mesh geometry={nodes.Shelf_B002_Shelf_B_0.geometry} material={materials.Shelf_B} />
			<mesh geometry={nodes.Shelf_B003_Shelf_B_0.geometry} material={materials.Shelf_B} />
			<mesh geometry={nodes.Shelf_B_G001_Shelf_B_0.geometry} material={materials.Shelf_B} />
			<mesh geometry={nodes.Shelf_C001_Shelf_C_0.geometry} material={materials.Shelf_C} />
			<mesh geometry={nodes.Shelf_F001_Shelf_F_0.geometry} material={materials.Shelf_F} />
			<mesh geometry={nodes.Shelf_fd002_Shelf_fd_0.geometry} material={materials.Shelf_fd} />
			<mesh geometry={nodes.Shelf_FR001_Shelf_FR_0.geometry} material={materials.Shelf_FR} />
			<mesh geometry={nodes.Shelf_FR002_Shelf_FR_0.geometry} material={materials.Shelf_FR} />
			<mesh geometry={nodes.Shelf_S001_Shelf_B_0.geometry} material={materials.Shelf_B} />
			<mesh geometry={nodes.Shelf_S002_Shelf_B_0.geometry} material={materials.Shelf_B} />
			<mesh geometry={nodes.Shelf_S003_Shelf_B_0.geometry} material={materials.Shelf_B} />
			<mesh geometry={nodes.Shelf_S004_Shelf_B_0.geometry} material={materials.Shelf_B} />
			<mesh geometry={nodes.Shelving001_Shelf_B_0.geometry} material={materials.Shelf_B} />
			<mesh geometry={nodes.Shelving001_Wire_0.geometry} material={materials.Wire} />
			<mesh geometry={nodes.Shelving002_Shelf_B_0.geometry} material={materials.Shelf_B} />
			<mesh geometry={nodes.Shelving002_Wire_0.geometry} material={materials.Wire} />
			<mesh geometry={nodes.Shelving003_Shelf_B_0.geometry} material={materials.Shelf_B} />
			<mesh geometry={nodes.Shelving003_Wire_0.geometry} material={materials.Wire} />
			<mesh geometry={nodes.Shelving004_Shelf_B_0.geometry} material={materials.Shelf_B} />
			<mesh geometry={nodes.Shelving004_Wire_0.geometry} material={materials.Wire} />
			<mesh geometry={nodes.sidewalk_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk001_AsphaltDamaged_0.geometry} material={materials.AsphaltDamaged} />
			<mesh geometry={nodes.sidewalk001_Grass_0.geometry} material={materials.Grass} />
			<mesh geometry={nodes.sidewalk001_Road_0.geometry} material={materials.Road} />
			<mesh geometry={nodes.sidewalk001_sidewalk_01_0.geometry} material={materials.sidewalk_01} />
			<mesh geometry={nodes.sidewalk002_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk002_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk003_AsphaltDamaged_0.geometry} material={materials.AsphaltDamaged} />
			<mesh geometry={nodes.sidewalk004_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk004_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk005_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk005_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk006_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk006_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk007_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk007_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk008_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk008_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk009_AsphaltDamaged_0.geometry} material={materials.AsphaltDamaged} />
			<mesh geometry={nodes.sidewalk010_AsphaltDamaged_0.geometry} material={materials.AsphaltDamaged} />
			<mesh geometry={nodes.sidewalk011_AsphaltDamaged_0.geometry} material={materials.AsphaltDamaged} />
			<mesh geometry={nodes.sidewalk012_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk012_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk013_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk013_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk014_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk014_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk015_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk015_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk016_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk016_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk017_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk017_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk018_AsphaltDamaged_0.geometry} material={materials.AsphaltDamaged} />
			<mesh geometry={nodes.sidewalk019_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk019_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk020_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk020_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk021_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk021_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk022_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk022_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk023_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk023_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk024_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk024_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk025_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk025_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.sidewalk026_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk027_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk028_sidewalk_0.geometry} material={materials.sidewalk} />
			<mesh geometry={nodes.sidewalk028_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.Soap_dispenser001_Soap_dispenser_0.geometry} material={materials.Soap_dispenser} />
			<mesh geometry={nodes.Soap_dispenser002_Soap_dispenser_0.geometry} material={materials.Soap_dispenser} />
			<mesh geometry={nodes.Soap_dispenser003_Soap_dispenser_0.geometry} material={materials.Soap_dispenser} />
			<mesh geometry={nodes.Soap_dispenser004_Soap_dispenser_0.geometry} material={materials.Soap_dispenser} />
			<mesh geometry={nodes.Soap_dispenser005_Soap_dispenser_0.geometry} material={materials.Soap_dispenser} />
			<mesh geometry={nodes.Soap_dispenser006_Soap_dispenser_0.geometry} material={materials.Soap_dispenser} />
			<mesh geometry={nodes.Soap_dispenser007_Soap_dispenser_0.geometry} material={materials.Soap_dispenser} />
			<mesh geometry={nodes.Soda_fountain_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Soda_fountain_Soda_fountain_0.geometry} material={materials.Soda_fountain} />
			<mesh geometry={nodes.Soda_fountain_01_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Soda_fountain_01_Soda_fountain_0.geometry} material={materials.Soda_fountain} />
			<mesh geometry={nodes.Table_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table001_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table002_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table003_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table004_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table005_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table006_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table007_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table008_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table009_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table010_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table011_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table012_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Table013_Table_0.geometry} material={materials.Table} />
			<mesh geometry={nodes.Toilet001_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet_T001_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet002_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet_T002_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet003_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet_T003_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet004_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet_T004_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet005_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet_T005_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet006_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet_T006_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet007_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Toilet_T007_Toilet_0.geometry} material={materials.Toilet} />
			<mesh geometry={nodes.Tree_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree001_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree002_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree003_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree004_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree005_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree006_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree007_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree008_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree009_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree010_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree011_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree012_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree013_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree014_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree015_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree016_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree017_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree018_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree019_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree020_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree021_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree022_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree023_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree024_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree025_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree026_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree027_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree028_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree029_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree030_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree031_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree032_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree033_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree034_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree035_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree036_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree037_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree038_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree039_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree040_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree041_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree042_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree043_Tree_0.geometry} material={materials.Tree} />
			<mesh geometry={nodes.Tree_01_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01001_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01002_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01003_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01004_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01005_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01006_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01007_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01008_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01009_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01010_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01011_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01012_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01013_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01014_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01015_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01016_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01017_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01018_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01019_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01020_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01021_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01022_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01023_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01024_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01025_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01026_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01027_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01028_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01029_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01030_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01031_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01032_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01033_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01034_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01035_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01036_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01037_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01038_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01039_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01040_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01041_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01042_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01043_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01044_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01045_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01046_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01047_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01048_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01049_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01050_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01051_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01052_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01053_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01054_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01055_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01056_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01057_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01058_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01059_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01060_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01061_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01062_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01063_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01064_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01065_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01066_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01067_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_01068_Tree_01_0.geometry} material={materials.Tree_01} />
			<mesh geometry={nodes.Tree_02_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02001_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02002_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02003_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02004_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02005_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02006_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02007_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02008_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02009_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02010_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02011_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02012_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02013_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02014_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02015_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02016_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02017_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02018_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02019_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02020_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_02021_Tree_02_0.geometry} material={materials.Tree_02} />
			<mesh geometry={nodes.Tree_03_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03001_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03002_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03003_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03004_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03005_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03006_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03007_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03008_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03009_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03010_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03011_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03012_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03013_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03014_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03015_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03016_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03017_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03018_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03019_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03020_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03021_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03022_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03023_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03024_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03025_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03026_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03027_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03028_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03029_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03030_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03031_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03032_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03033_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03034_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03035_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03036_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03037_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03038_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03039_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03040_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03041_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03042_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03043_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03044_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03045_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03046_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03047_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03048_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03049_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03050_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03051_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03052_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03053_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03054_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03055_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03056_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03057_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03058_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03059_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03060_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03061_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03062_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03063_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03064_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03065_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03066_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03067_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03068_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03069_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03070_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03071_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03072_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03073_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03074_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03075_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03076_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03077_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03078_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03079_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03080_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03081_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03082_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03083_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03084_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tree_03085_Tree_03_0.geometry} material={materials.Tree_03} />
			<mesh geometry={nodes.Tumbler_Tumbler_0.geometry} material={materials.Tumbler} />
			<mesh geometry={nodes.Tumbler001_Tumbler_0.geometry} material={materials.Tumbler} />
			<mesh geometry={nodes.Tumbler002_Tumbler_0.geometry} material={materials.Tumbler} />
			<mesh geometry={nodes.Tumbler003_Tumbler_0.geometry} material={materials.Tumbler} />
			<mesh geometry={nodes.Tumbler004_Tumbler_0.geometry} material={materials.Tumbler} />
			<mesh geometry={nodes.urinary001_Metal_0.geometry} material={materials.Metal} />
			<mesh geometry={nodes.urinary001_urinary_0.geometry} material={materials.urinary} />
			<mesh geometry={nodes.urinary002_Metal_0.geometry} material={materials.Metal} />
			<mesh geometry={nodes.urinary002_urinary_0.geometry} material={materials.urinary} />
			<mesh geometry={nodes.urinary003_Metal_0.geometry} material={materials.Metal} />
			<mesh geometry={nodes.urinary003_urinary_0.geometry} material={materials.urinary} />
			<mesh geometry={nodes.Ventilation_Ventilation_0.geometry} material={materials.Ventilation} />
			<mesh geometry={nodes.Ventilation001_Ventilation_0.geometry} material={materials.Ventilation} />
			<mesh geometry={nodes.Ventilation002_Ventilation_0.geometry} material={materials.Ventilation} />
			<mesh geometry={nodes.Ventilation003_Ventilation_0.geometry} material={materials.Ventilation} />
			<mesh geometry={nodes.Ventilation004_Ventilation_0.geometry} material={materials.Ventilation} />
			<mesh geometry={nodes.Ventilation005_Ventilation_0.geometry} material={materials.Ventilation} />
			<mesh geometry={nodes.Ventilation006_Ventilation_0.geometry} material={materials.Ventilation} />
			<mesh geometry={nodes.Ventilation007_Ventilation_0.geometry} material={materials.Ventilation} />
			<mesh geometry={nodes.Ventilation008_Ventilation_0.geometry} material={materials.Ventilation} />
			<mesh geometry={nodes.Ventilation009_Ventilation_0.geometry} material={materials.Ventilation} />
			<mesh geometry={nodes.Ventilation010_Ventilation_0.geometry} material={materials.Ventilation} />
			<mesh geometry={nodes.Ventilation011_Ventilation_0.geometry} material={materials.Ventilation} />
			<mesh geometry={nodes.Wall_W001_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W002_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W007_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W008_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W009_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W010_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W011_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W012_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W_D001_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W_D005_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W_D006_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W_D007_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W_D008_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Wall_W_D009_Wall_W_0.geometry} material={materials.Wall_W} />
			<mesh geometry={nodes.Washbasin001_Marble_0.geometry} material={materials.Marble} />
			<mesh geometry={nodes.Washbasin001_Metal_0.geometry} material={materials.Metal} />
			<mesh geometry={nodes.Washbasin002_Marble_0.geometry} material={materials.Marble} />
			<mesh geometry={nodes.Washbasin002_Metal_0.geometry} material={materials.Metal} />
			<mesh geometry={nodes.Washbasin003_Marble_0.geometry} material={materials.Marble} />
			<mesh geometry={nodes.Washbasin003_Metal_0.geometry} material={materials.Metal} />
			<mesh geometry={nodes.Windows_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Windows001_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Windows002_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Windows003_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Windows004_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Windows004_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Windows005_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Windows005_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Windows_Door_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Windows_Door001_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.Windows_Door002_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.Windows_Door003_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.Windows_Door004_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.Windows_Door005_Metal_0.geometry} material={materials.Metal} />
			<mesh geometry={nodes.Windows_Door006_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.Windows_Frame_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Windows_Frame001_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Windows_Frame002_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Windows_Frame003_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Windows_Frame004_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Windows_Frame005_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Windows_Frame006_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Windows_Frame007_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Windows_Frame008_Glass_0.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Windows_Frame008_MetalBare_0.geometry} material={materials.MetalBare} />
			<mesh geometry={nodes.Wood_Base_menu_burger_0.geometry} material={materials.menu_burger} />
			<mesh geometry={nodes.Wood_Base_Orange_0.geometry} material={materials.Orange} />
			<mesh geometry={nodes.Wood_Base_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.Wood_Base_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.Wood_Base001_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.Wood_Base001_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh geometry={nodes.Wood_Base002_Wood_0.geometry} material={materials.Wood} />
			<mesh geometry={nodes.Wood_Base002_WoodChips_0.geometry} material={materials.WoodChips} />
			<mesh
				geometry={nodes.WoodPlanksFloors0_WoodPlanksFloors0_0.geometry}
				material={materials.WoodPlanksFloors0}
			/>
		</group>
	);
}

useGLTF.preload("/models/Map/map.gltf");
