/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/pine-forest/source/pine.glb 
*/

import { useGLTF } from '@react-three/drei';
import { RigidBody } from '@react-three/rapier';

export default function Pine(props) {
	const { nodes, materials } = useGLTF('/models/pine-forest/source/pine.glb');

	console.log(nodes);

	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.pine1.geometry} material={materials.pine} receiveShadow />
			<mesh geometry={nodes.obj1.geometry} material={materials.mat1} receiveShadow />
			<mesh geometry={nodes.obj2.geometry} material={materials.mat2} receiveShadow />
		</group>
	);
}

useGLTF.preload('/models/pine-forest/source/pine.glb');
